Models/SanPham.cs
namespace NamCamera.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SanPham")]
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            BinhLuans = new HashSet<BinhLuan>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Key]
        [DisplayName("ID máy ảnh")]
        [Required(ErrorMessage = "Bạn phải nhập ID máy ảnh")]
        public int SanPhamID { get; set; }

        [DisplayName("Tên máy ảnh")]
        [Required(ErrorMessage = "Bạn phải nhập tên máy ảnh")]
        [StringLength(30)]
        public string TenSanPham { get; set; }

        [DisplayName("Hãng máy ảnh")]
        [Required(ErrorMessage = "Bạn phải nhập hãng máy ảnh")]
        [StringLength(30)]
        public string Hang { get; set; }

        [DisplayName("Giá nhập")]
        public double? GiaNhap { get; set; }

        [DisplayName("Giá bán")]
        [Required(ErrorMessage = "Bạn phải nhập giá bán")]
        public double GiaBan { get; set; }

        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Bạn phải nhập số lượng")]
        public int SoLuong { get; set; }

        [Column(TypeName = "text")]
        [DisplayName("Hình ảnh 01")]
        public string Anh01 { get; set; }

        [Column(TypeName = "text")]
        [DisplayName("Hình ảnh 02")]
        public string Anh02 { get; set; }

        [Column(TypeName = "text")]
        [DisplayName("Hình ảnh 03")]
        public string Anh03 { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập thông tin cho máy ảnh")]
        [StringLength(4000)]
        [DisplayName("Thông tin máy ảnh")]
        public string ThongTin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}

Controllers/QuanLySanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NamCamera.Models;
using PagedList;

namespace NamCamera.Controllers
{
    public class QuanLySanPhamsController : Controller
    {
        private Model1 db = new Model1();

        // GET: QuanLySanPhams
        public ActionResult Index(int? page)
        {
            var sanPhams = db.SanPhams.Include(s => s.BinhLuans);

            // sắp xếp phân trang
            sanPhams = sanPhams.OrderBy(e => e.SanPhamID);
            int pagesize = 5;

            int pageNumber = (page ?? 1);
            //return View(db.SanPhams.ToList());
            return View(sanPhams.ToPagedList(pageNumber, pagesize));
        }

        public ActionResult CapNhat(int? page)
        {
            var sanPhams = db.SanPhams.Include(s => s.BinhLuans);

            // sắp xếp phân trang
            sanPhams = sanPhams.OrderBy(e => e.SanPhamID);
            int pagesize = 10;

            int pageNumber = (page ?? 1);
            //return View(db.SanPhams.ToList());
            return View(sanPhams.ToPagedList(pageNumber, pagesize));
        }

        public ActionResult ThongKeHang()
        {
            int querySony = db.Database.SqlQuery<int>("select sum(SoLuong) from SanPham where Hang = 'Sony'").FirstOrDefault();
            int queryCanon = db.Database.SqlQuery<int>("select sum(SoLuong) from SanPham where Hang = 'Canon'").FirstOrDefault();
            int queryNikon = db.Database.SqlQuery<int>("select sum(SoLuong) from SanPham where Hang = 'Nikon'").FirstOrDefault();

            Session["Sony"] = querySony;
            Session["Canon"] = queryCanon;
            Session["Nikon"] = queryNikon;

            //int gia30 = db.Database.SqlQuery<int>("select count(TenSanPham) from SanPham where GiaNhap<30").FirstOrDefault();
            //int gia3070 = db.Database.SqlQuery<int>("select count(TenSanPham) from SanPham where GiaNhap>=30 and GiaNhap<=70").FirstOrDefault();
            //int gia70 = db.Database.SqlQuery<int>("select count(TenSanPham) from SanPham where GiaNhap>70").FirstOrDefault();

            //Session["Gia30"] = gia30;
            //Session["Gia3070"] = gia3070;
            //Session["Gia70"] = gia70;

            return View();
        }

        public ActionResult ThongKeMucGia()
        {
            //int querySony = db.Database.SqlQuery<int>("select sum(SoLuong) from SanPham where Hang = 'Sony'").FirstOrDefault();
            //int queryCanon = db.Database.SqlQuery<int>("select sum(SoLuong) from SanPham where Hang = 'Canon'").FirstOrDefault();
            //int queryNikon = db.Database.SqlQuery<int>("select sum(SoLuong) from SanPham where Hang = 'Nikon'").FirstOrDefault();

            //Session["Sony"] = querySony;
            //Session["Canon"] = queryCanon;
            //Session["Nikon"] = queryNikon;

            int gia30 = db.Database.SqlQuery<int>("select count(TenSanPham) from SanPham where GiaNhap<30").FirstOrDefault();
            int gia3070 = db.Database.SqlQuery<int>("select count(TenSanPham) from SanPham where GiaNhap>=30 and GiaNhap<=70").FirstOrDefault();
            int gia70 = db.Database.SqlQuery<int>("select count(TenSanPham) from SanPham where GiaNhap>70").FirstOrDefault();

            Session["Gia30"] = gia30;
            Session["Gia3070"] = gia3070;
            Session["Gia70"] = gia70;

            return View();
        }
        public ActionResult Xoa(int? page)
        {
            var sanPhams = db.SanPhams.Include(s => s.BinhLuans);

            // sắp xếp phân trang
            sanPhams = sanPhams.OrderBy(e => e.SanPhamID);
            int pagesize = 10;

            int pageNumber = (page ?? 1);
            //return View(db.SanPhams.ToList());
            return View(sanPhams.ToPagedList(pageNumber, pagesize));
        }
        // GET: QuanLySanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: QuanLySanPhams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QuanLySanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SanPhamID,TenSanPham,Hang,GiaNhap,GiaBan,SoLuong,Anh01,Anh02,Anh03,ThongTin")] SanPham sanPham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    sanPham.Anh01 = "";
                    sanPham.Anh02 = "";
                    sanPham.Anh03 = "";

                    var f1 = Request.Files["ImageFile1"];
                    if (f1 != null && f1.ContentLength> 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f1.FileName);
                        string UploadPath = Server.MapPath("~/Content/CameraImages/" + FileName);
                        f1.SaveAs(UploadPath);
                        sanPham.Anh01 = FileName;
                    }

                    var f2 = Request.Files["ImageFile2"];
                    if (f2 != null && f2.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f2.FileName);
                        string UploadPath = Server.MapPath("~/Content/CameraImages/" + FileName);
                        f2.SaveAs(UploadPath);
                        sanPham.Anh02 = FileName;
                    }

                    var f3 = Request.Files["ImageFile3"];
                    if (f3 != null && f3.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f3.FileName);
                        string UploadPath = Server.MapPath("~/Content/CameraImages/" + FileName);
                        f3.SaveAs(UploadPath);
                        sanPham.Anh03 = FileName;
                    }

                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                } 
                else
                {
                    ViewBag.Error = "Lỗi nhập dữ liệu";
                    return View(sanPham);
                }


            }
            catch (Exception ex)
            {
                ViewBag.Error = "ID của máy ảnh phải là duy nhất";
                return View(sanPham);

            }


        }

        // GET: QuanLySanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: QuanLySanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SanPhamID,TenSanPham,Hang,GiaNhap,GiaBan,SoLuong,Anh01,Anh02,Anh03,ThongTin")] SanPham sanPham)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var f1 = Request.Files["ImageFile1"];
                    if (f1 != null && f1.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f1.FileName);
                        string UploadPath = Server.MapPath("~/Content/CameraImages/" + FileName);
                        f1.SaveAs(UploadPath);
                        sanPham.Anh01 = FileName;
                    }

                    var f2 = Request.Files["ImageFile2"];
                    if (f2 != null && f2.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f2.FileName);
                        string UploadPath = Server.MapPath("~/Content/CameraImages/" + FileName);
                        f2.SaveAs(UploadPath);
                        sanPham.Anh02 = FileName;
                    }

                    var f3 = Request.Files["ImageFile3"];
                    if (f3 != null && f3.ContentLength > 0)
                    {
                        string FileName = System.IO.Path.GetFileName(f3.FileName);
                        string UploadPath = Server.MapPath("~/Content/CameraImages/" + FileName);
                        f3.SaveAs(UploadPath);
                        sanPham.Anh03 = FileName;
                    }

                    db.Entry(sanPham).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("CapNhat");

                }
                else
                {
                    ViewBag.Error = "Lỗi nhập dữ liệu";
                    return View(sanPham);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Xuất hiện lỗi " + ex.InnerException.Message + "<br/> Bạn phải nhập lại dữ liệu vào tất cả các trường";

Views/SanPhams/Create.cshtml
@model NamCamera.Models.SanPham

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SanPhamID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SanPhamID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SanPhamID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaNhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh01, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh01, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh01, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh02, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh02, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh02, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh03, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh03, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh03, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThongTin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThongTin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongTin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/SanPhams/Edit.cshtml
@model NamCamera.Models.SanPham

@{
    ViewBag.Title = "Edit";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <grammarly-extension data-grammarly-shadow-root="true" style="position: absolute; top: 0px; left: 0px; pointer-events: none;" class="cGcvT"></grammarly-extension><grammarly-extension data-grammarly-shadow-root="true" style="mix-blend-mode: darken; position: absolute; top: 0px; left: 0px; pointer-events: none;" class="cGcvT"></grammarly-extension>
        <div class="card-body">
            <h4 class="card-title">Thêm máy ảnh mới</h4>
            <p class="text-danger">@ViewBag.Error</p>
            @using (Html.BeginForm("Create", "QuanLySanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <span>
                            <span>
                                @Html.LabelFor(model => model.SanPhamID, htmlAttributes: new { @class = "control-label col-md-2" })
                            </span>
                            <span>
                                @Html.ValidationMessageFor(model => model.SanPhamID, "", new { @class = "text-danger" })
                            </span>
                        </span>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SanPhamID, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Hang, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.ValidationMessageFor(model => model.Hang, "", new { @class = "text-danger" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Hang, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.GiaNhap, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.ValidationMessageFor(model => model.GiaNhap, "", new { @class = "text-danger" })

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GiaNhap, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>


                    <div class="form-group">

                        @Html.LabelFor(model => model.Anh01, htmlAttributes: new { @class = "control-label col-md-2" })

                        <div class="col-md-10">
                            <img id="output1" class="img-rounded" alt="ảnh" width="300" height="200"
                                 src="~/Content/CameraImages/no image.png" />
                            <p>
                                <label for="ufile" style="cursor:pointer">Chọn file ảnh</label>
                                <input name="ImageFile1" id="ufile" type="file" style="display:inline-block;" onchange="loadFile1(event)" />

                            </p>
                            @*@Html.EditorFor(model => model.Anh01, new { htmlAttributes = new { @class = "form-control" } })*@
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Anh02, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.ValidationMessageFor(model => model.Anh02, "", new { @class = "text-danger" })

                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.Anh02, new { htmlAttributes = new { @class = "form-control" } })*@
                            <img id="output2" class="img-rounded" alt="ảnh" width="300" height="200"
                                 src="~/Content/CameraImages/no image.png" />
                            <p>
                                <label for="ufile" style="cursor:pointer">Chọn file ảnh</label>
                                <input name="ImageFile2" id="ufile" type="file" style="display:inline-block;" onchange="loadFile2(event)" />

                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Anh03, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.ValidationMessageFor(model => model.Anh03, "", new { @class = "text-danger" })

                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.Anh03, new { htmlAttributes = new { @class = "form-control" } })*@
                            <img id="output3" class="img-rounded" alt="ảnh" width="300" height="200"
                                 src="~/Content/CameraImages/no image.png" />
                            <p>
                                <label for="ufile" style="cursor:pointer">Chọn file ảnh</label>
                                <input name="ImageFile3" id="ufile" type="file" style="display:inline-block;" onchange="loadFile3(event)" />

                            </p>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ThongTin, htmlAttributes: new { @class = "control-label col-md-3" })
                        @Html.ValidationMessageFor(model => model.ThongTin, "", new { @class = "text-danger" })

                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ThongTin, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-primary mr-2">Thêm</button>
                            <button class="btn btn-light" type="reset">Hủy</button>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SanPhamID)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaNhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh01, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh01, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh01, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh02, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh02, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh02, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh03, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh03, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh03, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ThongTin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ThongTin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ThongTin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}