Models/TaiKhoan.cs
namespace NamCamera.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("TaiKhoan")]
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            BinhLuans = new HashSet<BinhLuan>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int TenID { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập tên đăng nhập")]
        [StringLength(30)]
        public string TenDangNhap { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập mật khẩu")]
        [StringLength(30)]
        public string MatKhau { get; set; }

        [Required]
        [StringLength(20)]
        public string Loai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}

Controllers/TaiKhoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NamCamera.Models;

namespace NamCamera.Controllers
{
    public class TaiKhoansController : Controller
    {
        private Model1 db = new Model1();

        // GET: TaiKhoans
        public ActionResult Index()
        {
            //return View(db.TaiKhoans.ToList());
            return View();
        }

        public ActionResult CheckLogin(string username, string password)
        {
            // lấy ra số tài khoản trong bảng TaiKhoan
            Int32 queryCount = db.Database.SqlQuery<Int32>("select count(TenID) from TaiKhoan").FirstOrDefault(); 

            for(int i=1; i<=queryCount; i++)
            {
                string queryUser = db.Database.SqlQuery<string>("select TenDangNhap from TaiKhoan where TenID = '" + i + "'").FirstOrDefault();
                string queryPass = db.Database.SqlQuery<string>("select MatKhau from TaiKhoan where TenID = '" + i + "'").FirstOrDefault();
                string queryType = db.Database.SqlQuery<string>("select Loai from TaiKhoan where TenID = '" + i + "'").FirstOrDefault();
                if (username == queryUser && password == queryPass)
                {
                   if (queryType == "user")
                    {
                        Session["user"] = username;
                        //Session["pass"] = password;
                        return RedirectToAction("Index", "SanPhams");
                    }
                   else
                    {
                        Session["user"] = username;
                        //Session["pass"] = password;
                        return RedirectToAction("Index", "QuanLySanPhams");
                    }
                }
            
            }
            ViewBag.error = "Tên đăng nhập hoặc mật khẩu không đúng";
            return View("Index");
        }

        public ActionResult Logout()
        {
            Session.Remove("user");
            return RedirectToAction("Index", "SanPhams");
        }

        // GET: TaiKhoans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // GET: TaiKhoans/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TaiKhoans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TenID,TenDangNhap,MatKhau,Loai")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(taiKhoan);
        }

        // GET: TaiKhoans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: TaiKhoans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TenID,TenDangNhap,MatKhau,Loai")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(taiKhoan);
        }

        // GET: TaiKhoans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: TaiKhoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TaiKhoans/Create.cshtml
@model NamCamera.Models.TaiKhoan

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaiKhoan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDangNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDangNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDangNhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Loai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Loai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/TaiKhoans/Delete.cshtml
@model NamCamera.Models.TaiKhoan

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TaiKhoan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenDangNhap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDangNhap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Loai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/TaiKhoans/Details.cshtml
@model NamCamera.Models.TaiKhoan

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TaiKhoan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenDangNhap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDangNhap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Loai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TenID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/TaiKhoans/Edit.cshtml
@model NamCamera.Models.TaiKhoan

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TaiKhoan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TenID)

        <div class="form-group">
            @Html.LabelFor(model => model.TenDangNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDangNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDangNhap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Loai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Loai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/TaiKhoans/Index.cshtml

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="clearfix"></div>

<div id="container" class="container">

    <main id="main" class="site-main row" role="main">
        <div id="content" class="col-md-8">



            <article id="post-7" class="post-7 page type-page status-publish hentry">

                <header class="entry-header">
                    <h1 class="post-title">Đăng nhập</h1>
                </header><!-- .entry-header -->

                <div class="entry-content">
                    <div class="woocommerce">
                        <div class="woocommerce-notices-wrapper"></div>


                        @using (Html.BeginForm("CheckLogin", "TaiKhoans",FormMethod.Post, new { @class = "woocommerce-form woocommerce-form-login login" }))
                        {
                    <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                        <label for="username">
                            Tên đăng nhập&nbsp;<span class="required">*</span>
                        </label>

                        <input type="text" class="woocommerce-Input woocommerce-Input--text input-text"
                               name="username" id="username" autocomplete="username" />
                        
                       

                    </p>
                            <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                <label for="password">Mật khẩu&nbsp;<span class="required">*
                                      </span></label>
                                <input class="woocommerce-Input woocommerce-Input--text input-text"
                                       type="password" name="password" id="password" 
                                       autocomplete="current-password" />
                            </p>


                            <p class="form-row">
                                <input type="hidden" id="woocommerce-login-nonce" name="woocommerce-login-nonce"
                                       value="6be26cffbd" /><input type="hidden" name="_wp_http_referer"
                                                                   value="/ocin-lite/my-account/" />
                                <button type="submit"
                                        class="woocommerce-button button woocommerce-form-login__submit"
                                        name="login" value="Log in">
                                    Đăng nhập
                                </button>
                                <span style="color:red">
                                    @ViewBag.error
                                </span>

                            </p>
                            <p class="woocommerce-LostPassword lost_password">
                                <a style="color:orange" href="#">Quên mật khẩu</a>
                            </p>
                        }

                        @*#region Form Login*@
                        <!--<form class="woocommerce-form woocommerce-form-login login" method="post">
                            <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                <label for="username">
                                    Tên đăng nhập&nbsp;<span class="required">( * )</span>
                                </label>
                                <input type="text" class="woocommerce-Input woocommerce-Input--text input-text"
                                       name="username" id="username" autocomplete="username" value="" />
                            </p>
                            <p class="woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide">
                                <label for="password">Mật khẩu&nbsp;<span class="required">*</span></label>
                                <input class="woocommerce-Input woocommerce-Input--text input-text"
                                       type="password" name="password" id="password"
                                       autocomplete="current-password" />
                            </p>


                            <p class="form-row">
                                <input type="hidden" id="woocommerce-login-nonce" name="woocommerce-login-nonce"
                                       value="6be26cffbd" /><input type="hidden" name="_wp_http_referer"
                                                                   value="/ocin-lite/my-account/" /> <button type="submit"
                                                                                                             class="woocommerce-button button woocommerce-form-login__submit"
                                                                                                             name="login" value="Log in">
                                    Log in
                                </button>


                            </p>
                            <p class="woocommerce-LostPassword lost_password">
                                <a style="color:orange" href="lost-password/index.html">Quên mật khẩu</a>
                            </p>


                        </form>-->
                        @*#endregion*@

                    </div>
                </div><!-- .entry-content -->

                <footer class="entry-footer">
                </footer><!-- .entry-footer -->
            </article><!-- #post-## -->



            <div class="clearfix"></div>
        </div><!-- /content -->

        <aside id="sidebar" class="col-md-4 widget-area" role="complementary">
            <aside id="recent-posts-2" class="widget widget_recent_entries">
                <h4 class="widget-title">Sản phẩm nổi bật</h4>
                <ul style="list-style-type:none;">

                    <li class="product type-product post-65 status-publish outofstock product_cat-furniture product_tag-metal has-post-thumbnail shipping-taxable purchasable product-type-variable">
                        <a href="/SanPhams/Details/1"
                           class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
                            <div class="product_thumbnail_wrap">
                                <img width="348" height="218"
                                     src="~/Content/CameraImages/Sony Alpha 01.jpg" 
                                     class="attachment-shop_catalog size-shop_catalog" alt=""
                                     srcset="~/Content/CameraImages/Sony Alpha 01.jpg 348w, ~/Content/CameraImages/Sony Alpha 01.jpg 300w, ~/Content/CameraImages/Sony Alpha 01.jpg 768w, ~/Content/CameraImages/Sony Alpha 01.jpg 1024w, ~/Content/CameraImages/Sony Alpha 01.jpg 197w, ~/Content/CameraImages/Sony Alpha 01.jpg 869w, ~/Content/CameraImages/Sony Alpha 01.jpg 1440w"
                                     sizes="(max-width: 348px) 100vw, 348px" />
                            </div>
                            <div class="product_text">
                                <h2 class="woocommerce-loop-product__title">Sony Alpha</h2>
                                <span class="price">
                                    <span class="woocommerce-Price-amount amount">
                                        <span class="woocommerce-Price-currencySymbol">Xem ngay</span>
                                    </span>
                                </span>
                            </div>
                        </a>
                    </li>

                </ul>

            </aside>
        </aside><!-- #sidebar -->


    </main><!-- #main -->

</div><!-- /#container -->